"""removed email column from Post table

Revision ID: a31307ae2243
Revises: 0ffc1f81dd0e
Create Date: 2021-06-01 13:57:06.596257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31307ae2243'
down_revision = '0ffc1f81dd0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
